version : "3.9"
name: "hunters"

services:
  cassandra-node-1:
    container_name: "cassandra-node-1"
    image: cassandra:3
    networks:
        - hunters-game-network
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "9042:9042"
  cassandra-node-2:
    container_name: "cassandra-node-2"
    image: cassandra:3
    networks:
        - hunters-game-network 
    environment:
      CASSANDRA_SEEDS: "cassandra-node-1"
    depends_on:
      cassandra-node-1:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5
  cassandra-node-3:
    container_name: "cassandra-node-3"
    image: cassandra:3
    restart: unless-stopped
    networks:
        - hunters-game-network
    environment:
      CASSANDRA_SEEDS: "cassandra-node-1, cassandra-node-2"
    depends_on:
      cassandra-node-2:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  hunters-game-network:
    name: "hunters-game-network"

